InternalTraining/Models/ContactUs.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace InternalTraining.Models
{
    public class ContactUs
    {
        public int Id { get; set; }

        public string CompanyName { get; set; }  
        [Required]
        [RegularExpression(@"^\+?\d{10,15}$", ErrorMessage = "Enter a valid phone number.")]
        public string Phone { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public int NumberOfEmployees { get; set; }

        public bool? IsSeen { get; set; }

        public  bool? IsAnswered { get; set; }

        public DateTime ExpectedTrainingDate { get; set; }
        [ValidateNever]
        public string Message { get; set; }

        public string? Token { get; set; }



    }
}

InternalTraining/Areas/Admin/Controllers/ContactUsController.cs
using InternalTraining.Unit_of_Work;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InternalTraining.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ContactUsController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        public ContactUsController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
            
        }
        public IActionResult Index()
        {
            var allMessage = unitOfWork.ContactsUs.Get().ToList();

            return View(allMessage);
        }

        public IActionResult ShowMess(int id)
        {
            var message = unitOfWork.ContactsUs.GetOne(e => e.Id == id);

            return View(message);
        }

        public IActionResult SendEmail(int id)
        {
            var message = unitOfWork.ContactsUs.GetOne(e => e.Id == id);

            return View();
        }


        public IActionResult Delete(int id)
        { 

            return View();
        }
    }
}

InternalTraining/Areas/Company/Controllers/ContactUsController.cs
using InternalTraining.Email_Sender;
using InternalTraining.Models;
using InternalTraining.Test_Cookie;
using InternalTraining.Unit_of_Work;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace InternalTraining.Areas.Company.Controllers
{
    [Area("Company")]
   
    public class ContactUsController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly IEmailSender emailSender;
  

        public ContactUsController(IUnitOfWork unitOfWork, IEmailSender emailSender)
        {
            this.unitOfWork = unitOfWork;
            this.emailSender = emailSender;
;
        }
        [HttpGet]
        public IActionResult Index()
        {


            return View();
        }
        // filling the form
        [HttpPost]
        public async Task<IActionResult> Index(ContactUs contact)
        {
                if (ModelState.IsValid)
                {
                    if (contact != null)
                    {
                        contact.Token = Guid.NewGuid().ToString();
                        unitOfWork.ContactsUs.Create(contact);
                        unitOfWork.Commit();
                    }

                    // send email to the company with a link of a page that it could enroll in a courses.

                    string subject = "Welcome to Mentor — Enroll in Courses";

                    // i need to adujst the direction of the link.. 

                    var link = Url.Action("AccessViaToken", "Home", new { area = "Company2", token = contact.Token }, Request.Scheme);

                    string body = $@"
                             <div style='font-family: Arial, sans-serif;'>
                             <h1 style='color: #143D60; font-weight: bold;'>Mentor</h1>
                             <p>Hello {contact.CompanyName},</p>
                             <p>Thank you for contacting us.</p>
                             <p>Please <a href='{link}' style='color: #1a73e8;'>click here</a> to enroll in our courses.</p>
                             <br/>
                                 <p>Best regards,<br/>Mentor Team</p>
                                      </div>";
                    await emailSender.SendEmailAsync(contact.Email, subject, body);

                    TempData["SuccessMessage"] = "Thank you for filling out the form. Please check your email.";

                    return RedirectToAction("Index", "Home", new { area = "Company" });
                }
                else

                {
                    return View(contact);
                }
           
        }
    }
}

InternalTraining/Areas/Company/Views/ContactUs/Index.cshtml
@model ContactUs
<main class="main">

    <!-- Page Title -->
    <div class="page-title" data-aos="fade">
        <div class="heading">
            <div class="container">
                <div class="row d-flex justify-content-center text-center">
                    <div class="col-lg-8">
                        <h1>Contact</h1>
                        <p class="mb-0">
                            We'd love to hear from you! Whether you have a question about our services, need support, or just want to say hello, feel free to reach out. Our team is always ready to help and will get back to you as soon as possible.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <nav class="breadcrumbs">
            <div class="container">
                <ol>
                    <li><a href="index.html">Home</a></li>
                    <li class="current">Contact</li>
                </ol>
            </div>
        </nav>
    </div><!-- End Page Title -->
    <!-- Contact Section -->
    <section id="contact" class="contact section">

        <div class="mb-5" data-aos="fade-up" data-aos-delay="200">
            <iframe style="border:0; width: 100%; height: 300px;" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d48389.78314118045!2d-74.006138!3d40.710059!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25a22a3bda30d%3A0xb89d1fe6bc499443!2sDowntown%20Conference%20Center!5e0!3m2!1sen!2sus!4v1676961268712!5m2!1sen!2sus" frameborder="0" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div><!-- End Google Maps -->

        <div class="container" data-aos="fade-up" data-aos-delay="100">

            <div class="row gy-4">

                <div class="col-lg-4">
                    <div class="info-item d-flex" data-aos="fade-up" data-aos-delay="300">
                        <i class="bi bi-geo-alt flex-shrink-0"></i>
                        <div>
                            <h3>Address</h3>
                            <p>A108 Adam Street, New York, NY 535022</p>
                        </div>
                    </div><!-- End Info Item -->

                    <div class="info-item d-flex" data-aos="fade-up" data-aos-delay="400">
                        <i class="bi bi-telephone flex-shrink-0"></i>
                        <div>
                            <h3>Call Us</h3>
                            <p>+1 5589 55488 55</p>
                        </div>
                    </div><!-- End Info Item -->

                    <div class="info-item d-flex" data-aos="fade-up" data-aos-delay="500">
                        <i class="bi bi-envelope flex-shrink-0"></i>
                        <div>
                            <h3>Email Us</h3>
                            <p>info@example.com</p>
                        </div>
                    </div><!-- End Info Item -->

                </div>

                <div class="col-lg-8">

                    <form asp-action="Index" asp-controller="ContactUs" method="post" class="php-email-form">
                        <div class="row gy-4">

                            <div class="col-md-6">
                                <input asp-for="CompanyName" class="form-control" placeholder="Company Name" />
                                <span asp-validation-for="CompanyName" class="text-danger"></span>
                            </div>

                            <div class="col-md-6">
                                <input asp-for="Email" class="form-control" placeholder="Email" />
                                <span asp-validation-for="Email" class="text-danger"></span>
                            </div>

                            <div class="col-md-12">
                                <input asp-for="Phone" class="form-control" placeholder="Phone" />
                                <span asp-validation-for="Phone" class="text-danger"></span>
                            </div>

                            <div class="col-md-12">
                                <input type="text" asp-for="NumberOfEmployees" class="form-control" placeholder="Number of Employees" />
                                <span asp-validation-for="NumberOfEmployees" class="text-danger"></span>
                            </div>

                            <div class="col-md-12">
                                <label class="form-label">Expected Training Date </label>
                                <input asp-for="ExpectedTrainingDate" class="form-control" type="date" placeholder="Expected Training Date" />
                                <span asp-validation-for="ExpectedTrainingDate" class="text-danger"></span>
                            </div>

                            <div class="col-md-12">
                                <textarea asp-for="Message" class="form-control" rows="6" placeholder="Message"></textarea>
                                <span asp-validation-for="Message" class="text-danger"></span>
                            </div>

                            <div class="col-md-12 text-center">
                                <button type="submit">Send Message</button>
                            </div>

                            <div class="col-md-12 text-center">
                                <div class="loading">Loading</div>
                                <div class="error-message"></div>
                                <div class="sent-message">Your message has been sent. Thank you!</div>
                            </div>

                        </div>
                    </form>
              </div><!-- End Contact Form -->

            </div>

        </div>

    </section><!-- /Contact Section -->

</main>